### ISSUE TITLE
No module named 'im2mesh'

### ISSUE THREAD

**Issue by Linxius** [yifita/iso-points#1]
When I'm trying to run test_dtu_points.py,  it comes out that:

Traceback (most recent call last):
  File "test_dtu_points.py", line 11, in <module>
    from im2mesh.checkpoints import CheckpointIO
ModuleNotFoundError: No module named 'im2mesh'

Could you help me with this?

**Comment by Linxius** [comment]
I find an im2mesh is provided in
https://github.com/autonomousvision/occupancy_networks
Is it THE im2mesh?

**Comment by Linxius** [comment]
> I find an im2mesh is provided in
> https://github.com/autonomousvision/occupancy_networks
> Is it THE im2mesh?

This works.

**Comment by QtEngineer** [comment]
Hi I cannot find config directory .how to fix it？
